#!/usr/bin/env bash

### PATH
if [ -d "$HOME/.bin" ]; then
	addToPath $HOME/.bin
fi

if [ -d "$HOME/.local/bin" ]; then
	addToPath $HOME/.local/bin
fi

if [ -d "$HOME/Applications" ]; then
	addToPath $HOME/Applications
fi

addToPath /usr/local/go/bin
addToPath $HOME/go/bin
addToPath $GOPATH/bin
addToPath $HOME/work/wrapper
addToPath $HOME/.yarn/bin
addToPath /usr/lib/llvm-8/bin
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup
addToPath $HOME/tools/lua-language-server/bin
addToPath $HOME/.ebcli-virtual-env/executables
addToPath $HOME/.config/rofi/bin
addToPath $HOME/.cargo/env
addToPath $HOME/.local/share/solana/install/active_release/bin
addToPath $HOME/Android/Sdk
addToPath $HOME/Android/Sdk/platform-tools
# ccache
addToPathFront /usr/lib/ccache
addToPath /home/luizcorreia/.local/share/gem/ruby/3.0.0/bin
addToPath $HOME/.rvm/bin
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
